CREATE SCHEMA IF NOT EXISTS UNIVERCITY;
USE UNIVERCITY;
CREATE TABLE IF NOT EXISTS MAJORS
(
MAJOR_ID INT(11) NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS STUDENTS 
(
STUDENT_ID INT(11) NOT NULL PRIMARY KEY,
STUEDENT_NUMBER INT(12) NOT NULL,
STUDENT_NAME VARCHAR(50) NOT NULL,
MAJOR_ID INT(11) NOT NULL,
CONSTRAINT FK_MAJOR_ID
FOREIGN KEY (MAJOR_ID)
REFERENCES MAJORS(MAJOR_ID) 
);  
CREATE TABLE IF NOT EXISTS PAYMENTS
(
PAYMENT_ID INT(11) NOT NULL PRIMARY KEY,
PAYMENT_DATE DATE NOT NULL,
PAYMENT_AMOUNT DECIMAL(8,2) NOT NULL,
STUDENT_ID INT(11) NOT NULL,
CONSTRAINT FK_STUDENT_ID_PAYMENT
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENTS(STUDENT_ID)
);
CREATE TABLE IF NOT EXISTS SUBJECTS
(
SUBJECT_ID INT(11) NOT NULL PRIMARY KEY,
SUBJECT_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS AGENDA 
(
STUDENT_ID INT(11) NOT NULL,
SUBJECT_ID INT(11) NOT NULL,
CONSTRAINT FK_STUDENT_ID_AGENDA
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENTS(STUDENT_ID),
CONSTRAINT FK_SUBJECT_ID
FOREIGN KEY (SUBJECT_ID)
REFERENCES SUBJECTS(SUBJECT_ID)
);
