CREATE SCHEMA IF NOT EXISTS SHOP;
USE SHOP;
CREATE TABLE IF NOT EXISTS CITIES
(
CITY_ID INT(11) NOT NULL PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS CUSTOMERS
(
 CUSTOMER_ID INT(11)NOT NULL PRIMARY KEY,
 NAME VARCHAR(50) NOT NULL,
 BIRTHDAY DATE NOT NULL,
 CITY_ID INT(11) NOT NULL,
 CONSTRAINT FK_CUSTOMER_CITY
 FOREIGN KEY (CITY_ID)
 REFERENCES CITIES(CITY_ID)
);
CREATE TABLE IF NOT EXISTS ORDERS
(
ORDER_ID INT(11) PRIMARY KEY NOT NULL,
CUSTOMER_ID INT(11) NOT NULL,
CONSTRAINT FK_CUSTOMER_ID
FOREIGN KEY (CUSTOMER_ID)
REFERENCES CUSTOMERS(CUSTOMER_ID)
);
CREATE TABLE ITEM_TYPES(
ITEM_TYPE_ID INT(11) PRIMARY KEY NOT NULL,
NAME VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS ITEMS
(
ITEM_ID INT(11) PRIMARY KEY NOT NULL,
NAME VARCHAR(50) NOT NULL,
ITEM_TYPE_ID INT(11) NOT NULL,
CONSTRAINT FK_ITEM_TYPE_ID
FOREIGN KEY (ITEM_TYPE_ID)
REFERENCES ITEM_TYPES(ITEM_TYPE_ID)
);
CREATE TABLE IF NOT EXISTS ORDER_ITEMS
(
ORDER_ID INT(11) NOT NULL,
ITEM_ID INT(11) NOT NULL,
CONSTRAINT FK_ORDER_ID
FOREIGN KEY (ORDER_ID)
REFERENCES ORDERS(ORDER_ID),
CONSTRAINT FK_ITEM_ID
FOREIGN KEY (ITEM_ID)
REFERENCES ITEMS(ITEM_ID)
);

